baseURL = "https://wasmcv.org"

title = 'wasmCV'

# defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
theme = "hermit-v2"

pygmentsCodefences  = true
pygmentsUseClasses  = true
#hasCJKLanguage = true

rssLimit = 10

copyright = "2024-2025 The Hybrid Group and friends"
enableEmoji = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.
  # category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # description = "wasmCV - WebAssembly interfaces for computer vision"
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = "WebAssembly interfaces for computer vision"
  footerCopyright = "The Hybrid Group and friends"
  
  footerHideThemeName = true
  # bgImg = ""

  justifyContent = false

  relatedPosts = false
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = false
  readTime = false
  shareSocial = true
  
  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/wasmvision"

  [[params.socialLinks]]
    name = "mastodon"
    url = "https://mastodon.social/@wasmvision"

  [[params.socialLinks]]
    name = "bsky"
    url = "https://bsky.app/profile/wasmvision.com"

[menu]
  [[menu.main]]
    name = "Documentation"
    url = "docs/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about-wasmcv/"
    weight = 20